pipelines:
  test:
    blubberfile: blubber.yaml
    stages:
      - name: test
  publish:
    blubberfile: blubber.yaml
    stages:
      - name: production
        build: prod
        publish:
          image:
            tags: [production]
        promote:
          - chart: apple-search
